spring:
  application:
    name: roleplay
  ai:
    alibaba:
      tool calling:
        time:
          enabled: true
        weather:
          enabled: true
        webSearch:
          enabled: true

    dashscope:
      api-key: sk-4337f91644ea48b6abdadf8bc3ff981c
      chat:
        options:
          model: qwen-plus
    websearch:
      api-key: sk-2f044e333ae64ba3b8c5e7bb7103f6e8
      url: https://api.bochaai.com/v1/web-search
    weather :
      api-key: SOhi8eJU_e7CEsHeP
  datasource:
    url: jdbc:mysql://111.229.209.82:3306/icht
    username: icht
    password: E8NMLcxNnJsnG8pZ
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis:
      host: 111.229.209.82
      port: 6379
      password: dust123
  kafka:
    bootstrap-servers: 111.229.209.82:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: icht-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              deafult:
                type: com.icht.backfront.model.Notify
            trusted:
              packages: *
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug
    com:
      dust:
        roleplay: debug